### PR TITLE
refactor away from kubectl provider

### PR DESCRIPTION
**Pull request by zack-is-cool**
fixes https://github.com/defenseunicorns/delivery-aws-iac/issues/335

### CODE REVIEW

**Review by ntwkninja — APPROVED** [review]
lgtm

**Comment by zack-is-cool** [comment]
I added another var just to allow people to override the default eniconfig creation if they have one already or wanted to just make their own (not through the addon) for whatever reason

**Review by ntwkninja — APPROVED** [review]
🚀

**Pull request merged**
